XMC4500-Barebone-Projects
=========================

This repository hosts various bare-bone embedded systems projects for the XMC4500 Cortex-M4 microcontroller from Infineon technologies AG. The examples target the http://www.mikrocontroller.net/articles/XMC4500[Relax Kit] evaluation boards available from http://www.ehitex.de/[Hitex] or http://www.infineon.com/[Infineon].

Instead of using the DAVE toolchain, the examples hosted here are cross-platform (Windows, OSX, and Linux) and are developed using a

* plain Makefile approach or a
* standard Eclipse CDT with the GNU ARM plugin installed.

NOTE: Checkout the documentation in the folder link:Setup/README.asciidoc[Setup] on how to install the toolchain.

== Getting Started

The folder Getting-Started hosts very fundamental getting started examples using

. the command-line
. a Makefile
. Eclipse-CDT

For either example a simple step-by-step description is available.

== Various Examples

The following folders contain various examples - either import them into your eclipse workspace using File -> Import -> General -> Archive File ... or extract them and make use of the Makefile (see the comments within the Makefile for usage instructions).

* link:IO_Examples[IO Examples]
* link:Debugging[Debug-Interface Examples]
* link:Timer[Timer Examples]
* ADC/DAC Examples
* USIC Examples
* link:USB_Examples[USB Examples]

NOTE: There are also several bare-bone examples (without using DAVE) available from infineon.com -> Products -> 32-bit Industrial Microcontroller based on ARM Cortex-M -> Cortex-M4 -> Application Notes and Articles. For example, several applications using the VADC in variopus settings.