MAC OS-X Setup
==============
:author: Martin Horauer
:doctype: article
:toc: right
:icons: font
:data-uri:
:lang: en
:date: 2014
:encoding: iso-8859-1
:src: c
:docinfo:


== GNU Tools for ARM Embedded

Download https://launchpad.net/gcc-arm-embedded/+download[GNU Tools for ARM Embedded Processors] and install it with:

....
$ mkdir -p $HOME/bin; cd $HOME/bin
$ tar xjf gcc-arm-none-eabi-4_8-2014q2-20140609-mac.tar.bz2
$ sudo echo '$HOME/bin/gcc-arm-none-eabi-4_8-2014q2/bin' /etc/paths
$ rm -rf gcc-arm-none-eabi-4_8-2014q2-20140609-mac.tar.bz2 
....

WARNING: In case a newer version is available, adjust the filenames in the above commands.

To verify the installation start a new shell and enter `arm-none` followed by hitting the TAB krey two times. The output should look similar to the one below.

....
$ arm-none-eabi-
arm-none-eabi-addr2line   arm-none-eabi-gcc-4.8.4   arm-none-eabi-nm
arm-none-eabi-ar          arm-none-eabi-gcc-ar      arm-none-eabi-objcopy
arm-none-eabi-as          arm-none-eabi-gcc-nm      arm-none-eabi-objdump
arm-none-eabi-c++         arm-none-eabi-gcc-ranlib  arm-none-eabi-ranlib
arm-none-eabi-c++filt     arm-none-eabi-gcov        arm-none-eabi-readelf
arm-none-eabi-cpp         arm-none-eabi-gdb         arm-none-eabi-size
arm-none-eabi-elfedit     arm-none-eabi-gprof       arm-none-eabi-strings
arm-none-eabi-g++         arm-none-eabi-ld          arm-none-eabi-strip
arm-none-eabi-gcc         arm-none-eabi-ld.bfd      
....

== SEGGER J-Link

Download and install the respective http://www.segger.com/jlink-software.html[SEGGER J-Link software & documentation pack for MAC OS-X]. 

To verify the installation run `JLinkExe` from the `terminal` prompt.

== Eclipse-CDT

First download and install the http://www.java.com/en/download/manual.jsp?locale-=en[JAVA JDK from Oracle].

Download the http://www.eclipse.org/downloads/packages/eclipse-ide-cc-developers/keplersr2[Eclipse CDT] package and extract it to a suitable directory, e.g., `$HOME/bin`. Modify the path variable to point to the `eclipse` executable, e.g.:

....
$ sudo echo "$HOME/bin/eclipse" >> /etc/paths
....

You may draw the `Eclipse.app` into the launcher.



