Windows Toolchain Installation & Setup
======================================
:author: Martin Horauer
:doctype: article
:toc: right
:icons: font
:data-uri:
:lang: en
:date: 2014
:encoding: iso-8859-1
:src: c
:docinfo:

Since the standard windows command prompt has rather limited capabilities, I recommend to use the free http://technet.microsoft.com/en-us/scriptcenter/dd742419.aspx[PowerShell]. Furhermore, add a right-click menu to the file explorer (see below).

[WARNING]
[red]#Beware of installation in paths using Spaces or other non-ASCII characters. Even the default dialogs may result in non-functional setups. Better install the tools in a directory like `C:\essd`.
Likewise, beware of virtual folders. Make all file-extensions visible. Add the folders to the programs to your `PATH` variable.#

== GNU Tools for ARM Embedded

Download the http://fhe.technikum-wien.at/~horauer/xmc/gcc-arm-none-eabi-4_8-2014q2-20140609-win32.exe[GNU Tools for ARM Embedded installer] and execute it. When asked to modify the +PATH+ variable let the installer do it.

== SEGGER J-Link

Download and install the respective http://www.segger.com/jlink-software.html[SEGGER J-Link software & documentation pack for Windows]

== Eclipse-CDT

Determine whether you are running a 32-bit or 64-bit copy of Windows via the _System Settings_.

First download and install the http://www.java.com/en/download/manual.jsp?locale-=en[JAVA JDK from Oracle].

Next, you'll need a `make.exe` utility. To that end, install either http://www.mingw.org/[MinGW] or http://www.codeblocks.org[CodeBlocks with MinGW]. Copy and rename the `mingw32-make.exe` program in the `MinGW\bin` folder to `make.exe`. Finally, modify the +PATH+ variable of your system to point to this location.

Download and install the respective http://eclipse.org/downloads/packages/eclipse-ide-cc-developers/keplersr2[Eclipse] version.
